import { useState } from 'react'
import { Character } from '@/types/character-card'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Send, Trash2, RefreshCw } from 'lucide-react'

interface TestingTabProps {
  character: Character
}

interface Message {
  role: 'user' | 'assistant'
  content: string
}

export default function TestingTab({ character }: TestingTabProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      content: character.first_mes || 'Hello!',
    },
  ])
  const [input, setInput] = useState('')

  const handleSend = () => {
    if (!input.trim()) return

    const newMessages = [...messages, { role: 'user' as const, content: input }]
    setMessages(newMessages)
    setInput('')

    // Simulate AI response (in real app, this would call an AI API)
    setTimeout(() => {
      setMessages([
        ...newMessages,
        {
          role: 'assistant',
          content: `[This is a mock response. In production, this would be generated by an AI based on the character's personality and context.]`,
        },
      ])
    }, 500)
  }

  const handleReset = () => {
    setMessages([
      {
        role: 'assistant',
        content: character.first_mes || 'Hello!',
      },
    ])
  }

  const handleClear = () => {
    setMessages([])
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Chat Sandbox</CardTitle>
              <CardDescription>
                Test your character in a simulated conversation
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={handleReset}>
                <RefreshCw className="h-4 w-4 mr-2" />
                Reset
              </Button>
              <Button variant="outline" size="sm" onClick={handleClear}>
                <Trash2 className="h-4 w-4 mr-2" />
                Clear
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="border rounded-lg overflow-hidden">
            <ScrollArea className="h-[500px] p-4">
              <div className="space-y-4">
                {messages.map((message, index) => (
                  <div
                    key={index}
                    className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div
                      className={`max-w-[80%] rounded-lg px-4 py-2 ${
                        message.role === 'user'
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-muted'
                      }`}
                    >
                      <p className="text-sm whitespace-pre-wrap">{message.content}</p>
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>

            <div className="border-t p-4 bg-muted/50">
              <div className="flex gap-2">
                <Textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault()
                      handleSend()
                    }
                  }}
                  placeholder="Type your message... (Enter to send, Shift+Enter for new line)"
                  className="min-h-[60px] resize-none"
                />
                <Button onClick={handleSend} size="icon" className="shrink-0">
                  <Send className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Prompt Preview</CardTitle>
          <CardDescription>
            How the character data is composed for the AI
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div>
              <h4 className="text-sm font-semibold mb-2">System Prompt</h4>
              <pre className="bg-muted p-3 rounded text-xs overflow-x-auto">
                {character.system_prompt || 'You are roleplaying as {{char}}.'}
              </pre>
            </div>

            <div>
              <h4 className="text-sm font-semibold mb-2">Character Context</h4>
              <pre className="bg-muted p-3 rounded text-xs overflow-x-auto">
                {`Name: ${character.name}
Description: ${character.description}
Personality: ${character.personality}
Scenario: ${character.scenario}`}
              </pre>
            </div>

            {character.character_book && character.character_book.entries.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold mb-2">
                  Lorebook ({character.character_book.entries.filter(e => e.constant).length} constant entries)
                </h4>
                <pre className="bg-muted p-3 rounded text-xs overflow-x-auto max-h-[200px]">
                  {character.character_book.entries
                    .filter(e => e.constant)
                    .map(e => e.content)
                    .join('\n\n')}
                </pre>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
